crab status --verboseErrors crab_projects/crab_clustAlg_dataA_2018_nom_AltDatasets_000
crab status --verboseErrors crab_projects/crab_clustAlg_dataB_2018_nom_AltDatasets_000
crab status --verboseErrors crab_projects/crab_clustAlg_dataC_2018_nom_AltDatasets_000
crab status --verboseErrors crab_projects/crab_clustAlg_dataD_2018_nom_AltDatasets_000
