crab status -d crab_projects/crab_clustAlg_dataB_2017_nom_AltDatasets_000
crab status -d crab_projects/crab_clustAlg_dataC_2017_nom_AltDatasets_000
crab status -d crab_projects/crab_clustAlg_dataD_2017_nom_AltDatasets_000
crab status -d crab_projects/crab_clustAlg_dataE_2017_nom_AltDatasets_000
crab status -d crab_projects/crab_clustAlg_dataF_2017_nom_AltDatasets_000
