crab submit -c crab_clusteringAnalyzer_dataA_2018_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_dataG_2016_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataC-HIPM_2016_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataE-HIPM_2015_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataF-HIPM_2015_cfg.py
crab submit -c crab_clusteringAnalyzer_dataF_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_dataH_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_dataF_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_dataC-HIPM_2015_cfg.py
crab submit -c crab_clusteringAnalyzer_dataA_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_dataF_2016_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataF_2017_JEC_cfg.py
