crab resubmit -d crab_projects/crab_clustAlg_dataB-ver1_2015__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataB-ver2_2015__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataC-HIPM_2015__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataD-HIPM_2015__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataE-HIPM_2015__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataF-HIPM_2015__AltDatasets_000
