crab resubmit -d crab_projects/crab_clustAlg_dataA_2018__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataB_2018__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataC_2018__AltDatasets_000
crab resubmit -d crab_projects/crab_clustAlg_dataD_2018__AltDatasets_000
