crab submit -c crab_clusteringAnalyzer_ST_s-channel-hadronsMC_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_s-channel-leptonsMC_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_t-channel-antitop_inclMC_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_t-channel-top_inclMC_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_tW-antiTop_inclMC_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_tW-top_inclMC_2018_cfg.py

crab submit -c crab_clusteringAnalyzer_TTJetsMCHT1200to2500_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_TTJetsMCHT2500toInf_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_QCDMC1000to1500_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_QCDMC2000toInf_2018_cfg.py
crab submit -c crab_clusteringAnalyzer_QCDMC1500to2000_2018_cfg.py
