crab submit -c crab_clusteringAnalyzer_ST_s-channel-hadronsMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_s-channel-leptonsMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_t-channel-antitop_inclMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_t-channel-top_inclMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_tW-antiTop_inclMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_ST_tW-top_inclMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_TTToHadronicMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_TTToLeptonicMC_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_TTToSemiLeptonicMC_2016_JEC_cfg.py

crab submit -c crab_clusteringAnalyzer_QCDMC1000to1500_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_QCDMC2000toInf_2016_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_QCDMC1500to2000_2016_JEC_cfg.py
