crab submit -c crab_clusteringAnalyzer_dataA_2018_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_dataB_2018_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_dataC_2018_JEC_cfg.py
crab submit -c crab_clusteringAnalyzer_dataD_2018_JEC_cfg.py