crab submit -c crab_clusteringAnalyzer_dataB_2017_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataC_2017_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataD_2017_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataE_2017_JER_cfg.py
crab submit -c crab_clusteringAnalyzer_dataF_2017_JER_cfg.py