crab submit -c crab_CreateEfficiencyMapHists_TTToSemiLeptonicMC_2016_cfg.py
crab submit -c crab_CreateEfficiencyMapHists_TTToLeptonicMC_2016_cfg.py
crab submit -c crab_CreateEfficiencyMapHists_TTbarMC_2016_cfg.py
