crab submit -c crab_selectionStudier_ST_s-channel-hadronsMC_2015_cfg.py
crab submit -c crab_selectionStudier_ST_s-channel-hadronsMC_2016_cfg.py
crab submit -c crab_selectionStudier_ST_s-channel-hadronsMC_2017_cfg.py
crab submit -c crab_selectionStudier_ST_s-channel-hadronsMC_2018_cfg.py
crab submit -c crab_selectionStudier_ST_s-channel-leptonsMC_2015_cfg.py
crab submit -c crab_selectionStudier_ST_s-channel-leptonsMC_2016_cfg.py
crab submit -c crab_selectionStudier_ST_s-channel-leptonsMC_2017_cfg.py
crab submit -c crab_selectionStudier_ST_s-channel-leptonsMC_2018_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-antitop_inclMC_2015_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-antitop_inclMC_2016_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-antitop_inclMC_2017_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-antitop_inclMC_2018_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-top_inclMC_2015_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-top_inclMC_2016_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-top_inclMC_2017_cfg.py
crab submit -c crab_selectionStudier_ST_t-channel-top_inclMC_2018_cfg.py
crab submit -c crab_selectionStudier_ST_tW-antiTop_inclMC_2015_cfg.py
crab submit -c crab_selectionStudier_ST_tW-antiTop_inclMC_2016_cfg.py
crab submit -c crab_selectionStudier_ST_tW-antiTop_inclMC_2017_cfg.py
crab submit -c crab_selectionStudier_ST_tW-antiTop_inclMC_2018_cfg.py
crab submit -c crab_selectionStudier_ST_tW-top_inclMC_2015_cfg.py
crab submit -c crab_selectionStudier_ST_tW-top_inclMC_2016_cfg.py
crab submit -c crab_selectionStudier_ST_tW-top_inclMC_2017_cfg.py
crab submit -c crab_selectionStudier_ST_tW-top_inclMC_2018_cfg.py
